

export const DECLARATION_FIELDS = [
  'ALICI VKN',
  'Alıcı',
  'KONTEYNER NO',
  'Teslim şekli',
  'Brüt KG',
  'SON AMBAR',
  'ÖZET BEYAN NO',
  'BEYANNAME TESCİL TARİHİ',
  'TAREKS-TARIM-TSE',
];

export const FREIGHT_FIELDS = [
  'Nakliyeci',
  'Fat. Tarihi',
  'Tahmini Çıkış Tarihi',
  'Varış Tarihi',
  'TT',
  'Çıkış Limanı',
  'Varış Limanı',
  'HAT',
  'Navlun Fatura Tutarı',
  'Hacim',
  'w/m navlun',
  'Rakip EXW / FCA',
  'All in Fatura Tutarı',
  'Öykü Dönem Navlun w/m',
  'Total Fark w/m',
  'KAYIT TARİHİ',
  'D.Ö.',
];

export const FIELD_LABELS: { [key: string]: string } = {
  // Declaration Fields
  'Alıcı': 'Alıcı',
  'ALICI VKN': 'Alıcı VKN',
  'KONTEYNER NO': 'Konteyner No',
  'Teslim şekli': 'Teslim Şekli',
  'Brüt KG': 'Brüt KG',
  'SON AMBAR': 'Son Ambar',
  'ÖZET BEYAN NO': 'Özet Beyan No',
  'BEYANNAME TESCİL TARİHİ': 'Beyanname Tescil Tarihi',
  'TAREKS-TARIM-TSE': 'TAREKS-TARIM-TSE',
  // Freight Fields
  'D.Ö.': 'D.Ö.',
  'Nakliyeci': 'Nakliyeci',
  'Fat. Tarihi': 'Fat. Tarihi',
  'Tahmini Çıkış Tarihi': 'Tahmini Çıkış Tarihi',
  'Varış Tarihi': 'Varış Tarihi',
  'TT': 'TT',
  'Çıkış Limanı': 'Çıkış Limanı',
  'Hacim': 'Hacim',
  'w/m navlun': 'w/m Navlun',
  'Navlun Fatura Tutarı': 'Navlun Fatura Tutarı',
  'Rakip EXW / FCA': 'Rakip EXW / FCA',
  'All in Fatura Tutarı': 'All in Fatura Tutarı',
  'Öykü Dönem Navlun w/m': 'Öykü Dönem Navlun w/m',
  'Total Fark w/m': 'Total Fark w/m',
  'Varış Limanı': 'Varış Limanı',
  'HAT': 'HAT',
  'KAYIT TARİHİ': 'Kayıt Tarihi',
};

export const EXCEL_EXPORT_ORDER = [
  'Beyanname Dosya Adı', 
  'Navlun Dosya Adı', 
  'Alıcı',
  'D.Ö.',
  'ALICI VKN', 
  'Nakliyeci', 
  'Fat. Tarihi', 
  'Tahmini Çıkış Tarihi', 
  'Varış Tarihi', 
  'TT',
  'Çıkış Limanı', 
  'KONTEYNER NO', 
  'Teslim şekli', 
  'Brüt KG', 
  'Hacim', 
  'Navlun Fatura Tutarı', 
  'w/m navlun',
  'Rakip EXW / FCA', 
  'All in Fatura Tutarı', 
  'Öykü Dönem Navlun w/m', 
  'Total Fark w/m', 
  'Varış Limanı', 
  'SON AMBAR', 
  'HAT', 
  'ÖZET BEYAN NO', 
  'BEYANNAME TESCİL TARİHİ', 
  'TAREKS-TARIM-TSE', 
  'KAYIT TARİHİ'
];